### ISSUE TITLE
request school

### ISSUE THREAD

**Issue by rezaqees** [soroushamdg/acd#1]
plz add my school 
79.143.84.172/

**Comment by soroushamdg** [comment]
link shomare ezafe kardm, faght bara inke moshkeli pish nayad akharin release ro az ["releases" ](https://github.com/soroushamdg/acd/releases/tag/v1.0.1) download konin, dafe haye bad faght kafie database ro download konin na release jadid.
lotfan app ro be doostatoon ham moarefi konid.
enjoy:p

**Comment by rezaqees** [comment]
SALAM MAMNON TEST KARDAM AMA LOGIN FILD MISHOD

**Comment by soroushamdg** [comment]
error khassi to cmd neshoon midad?

**Comment by soroushamdg** [comment]
Chon linki hast ke kharej az daneshgah ha boode, yekam momkene ezafe kardanash zaman bar bashe,
linke login http://79.143.84.172/system/login hast dg?
bad ke login mikonid khodetoon, too che safhe ii mire?

**Comment by soroushamdg** [comment]
لینکتون رو چک کردم، درست کار میکنه، یوزر نیم پسوورد رو چک کنید

**Comment by rezaqees** [comment]
سلام هرکاری کردم وارد نشد یوزر و پسورد جدید هم ساختم فک میکنم بخاطر اینکه این روت اصلی پنله لطفا این لینک رو اضافه کن 
http://79.143.84.172/icdl

**Comment by 9713623** [comment]
plz add my school    
http://79.143.84.172/http://www.adi.ac.ir/

**Comment by 9713623** [comment]
http://www.adi.ac.ir/       
نمیتونم لاگین کنم دانشگام موسسه دهخدای قزوینه لطفا کمک کنید

**Comment by semnanuniversity** [comment]
سلام لطفا لینک دانشگاه سمنان رو هم اضافه کنید
لینکهای ادبی کانکت آن:
vc.semnan.ac.ir
vc1.semnan.ac .ir  تا vc15.semnan.ac.ir
vc69.semnan.ac.ir
از تسریع در امور سپاسگزارم.
