### ISSUE TITLE
Make it Open Source and publish Mac, Linux Version

### ISSUE THREAD

**Issue by amir28** [soroushamdg/acd#10]
چرا این برنامه اوپن سورس نیست؟؟ موقع اجرا کردنش به دلیل وجود آندرلاین توی یوزر نرمم برنامه اجرا نمی‌شد. چرا اوپن سورسش نمی‌کنین که این باگ‌ها سریعا حل بشن. در ضمن فکر کنم چون که با پایتون و کیوت نوشته شده خیلی راحت بشه به لینوکس و مک هم پورتش کرد. ممنون

**Comment by soroushamdg** [comment]
سلام، اوپن سورس بودنش چنتا مشکل داره مهم ترینش اینکه اگه برنامه اوپن سورس بشه، توزیع های مختلف و غیر قابل کنترلی ازش درمیان که این موضوع باعث میشه اگر تعداد تقاضا دانلود ها برای یک دانشگاه بره بالا ممکنه سرور های اون دانشگاه داون بشه و اگر این موضوع، رو دانشگاه های بیشتری تاثیر بذاره، متوقف کردن دانلودر ها غیر ممکنه و خب ازونطرف هزینه و خسارت زیادی ممکنه ایجاد کنه. چون هردفعه که سرور ها برگردن و لایو شن، دوباره فشار روشون میاد و به مشکل برمیخورن، که این باعث میشه استادا کلاسای روزانه رو هم نتونن برگزار کنن. من خودم با اپن سورس بودنش مشکل ندارم، خیلی هم خوبه و بار رو از روی دوش من برمیداره، ولی خب اگر مشکلی هم پیش بیاد، باید یجور بشه جمعش کرد.

**Comment by amir28** [comment]
بیش‌تر منظور از اوپن سورس شدن، اوپن سورس شدن نرم‌افزار بود که باگ‌هاش برطرف بشن. می‌تونین دیتاهای دیتابیس رو منشر نکنین.
اینجوری دیگه توزیع‌های مختلف دیگه درست نمی‌شن و فقط باگ‌های نرم‌افزار حل میشه
