### ISSUE TITLE
Request School

### ISSUE THREAD

**Issue by sjdyz** [soroushamdg/acd#104]
please add shiraz university to schools

http://vc69.shirazu.ac.ir/

www.shirazu.ac.ir

http://vc23.shirazu.ac.ir/penjx7cc9050/?OWASP_CSRFTOKEN=cc65a2e79f8c7f5455a5ec4bf3549dcb49370f453bb6033b7dd36f849025c2e2&proto=true

**Comment by soroushamdg** [comment]
سلام نمونه لینک کار نمیکنه

**Comment by sjdyz** [comment]
> سلام نمونه لینک کار نمیکنه

سلام وقتتون بخیر میشه این لینک رو هم امتحان کنید؟

http://vc69.shirazu.ac.ir/pv0i4pc2ruvv/

**Comment by sjdyz** [comment]
> > سلام نمونه لینک کار نمیکنه
> 
> سلام وقتتون بخیر میشه این لینک رو هم امتحان کنید؟
> 
> http://vc69.shirazu.ac.ir/pv0i4pc2ruvv/
> 
> فقط من با اون روشی که آخر لینک باید ی متنی اضافی کنیم دانلود میکنم فایلارو ولی فقط صدا دارن و تصویر ندارن اونارو چجوری حل کنم؟
> 
> منظورم این متنه که به آخر لینک کلاس اضافش میکنم
> 
> /output/filename.zip?download=zip

جناب وقتتون بخیر ممکنه این پیام رو مجدد چک کنید؟
ممنون
