### ISSUE TITLE
request lms.bkatu.ac.ir

### ISSUE THREAD

**Issue by mohammadreza1997** [soroushamdg/acd#107]
request lms.bkatu.ac.ir

**Comment by soroushamdg** [comment]
سلام
لطفا نمونه لینک کلاس ضبط شده بفرستید

**Comment by mohammadreza1997** [comment]
http://vc.bkatu.ac.ir/padd11g9wm4j/
با تشکر
همینجوری توی برنامه یه دانشگاه الکی زدم لینک دادم دان کرد ولی توی پوشه export  تو دسکتاپ فایلی نبود

**Comment by mohammadreza1997** [comment]
مهندس چیشد امتحانا دارن شروع میشن
