### ISSUE TITLE
ارور نام کاربري و رمز عبور اشتباه دانشگاه صنعتي سهند

### ISSUE THREAD

**Issue by vahedjbedu** [soroushamdg/acd#108]
سلام 
من کارايي که تو فيلم گفته بودن کردم دانشگاهمم توي ليست هست
دانشگاه صنعتي سهند           95.80.184.253
همه چيش اوکيه ولي ارور ميده
موقع وارد کردن نام کاربري که همون شماره دانشجويي هس و رمز عبور که برا دوستم کد ملي بود ولي من عوض کرده بودم رمزمو ارور داد که نام کاربري يا رمز عبور اشتباهه. برا جفتمونم ارور داد
هم مال دوستمو امتحان کردم که رمزو عوض نکرده بود هم خودم که عوض کرده بودم کار نکرد و همون ارور داد برا جفتمونم
ميشه خاهشا راهکار بگين برامون؟ امتحانات چند زروز مونده شروع شه  و خيلي سريع ي راهکار نياز داريم برا اين مشکل
 با تشکر خيلي ممنون متشکرم

**Comment by nimanmy** [comment]
سلام 
مشکل دانشگاه سهند حل نشده هنوز؟

**Comment by vahedjbedu** [comment]
نه متاسفانه
رمز عبور و نام کاربریم درسته ولی میزنه اشتباه وارد کردم
موقع امتحاناس نیاز داریم
حتا قبلنم خیلی گشتم پیدا نکرده بودم، دیشب تفننی سرچ کردم گیتهابو اورد دگ ی
جورایی امیدوار شدم
ممنون میشم اون مشکلو حل کنید

**Comment by soroushamdg** [comment]
سلام مشکل از طرف نرم افزار رفع شده
من چندبار تست کردم فایل ها دانلود شدن
احتمالا سرور های دانشگاه اخیرا بلاک میکنه یا مورد دیگه ای باشه
لطفا اخرین نسخه رو دانلود کنید و یدور دیگه امتحان کنید

**Comment by vahedjbedu** [comment]
سلام مهندس
شبتون بخیر باشه انشاءالله
شرمنده دیروقت ایمیل میدم
بله دستتون درد نکنه خیلی ممنون مشکل لاگین ل شده
ولی الان ی مشکل دگ هس
اونم اینکه فایل های دانلودی بدون ویدیو هستن
منظور اینکه فقط ویس استاد دانلود شده
ویدیوها دانلود نشده
میشع لطف کنید این مشکلم حل کنید
شرمنده، زحمات ما زیاد شد
دستتون درد نکنه،خیلی ممنونم

**Comment by vahedjbedu** [comment]
سلام برادر
ببخشید مزاحم شدم
اقا الان لاگین دانشگاه سهند حل شده خدارو شکر
ولی فیلما دانلود نمیشن
فقط ویس ضبط میشه
میشه بفرمایید چیکار کنیم فیلم هم دانلود بشه؟
با تشکر
