### ISSUE TITLE
اضافه کردن دانشگاه صنعتی همدان

### ISSUE THREAD

**Issue by pourias1999** [soroushamdg/acd#109]
http://lms.hut.ac.ir/
http://lms.hut.ac.ir/linear_control_azimi

**Comment by soroushamdg** [comment]
اضافه شد

**Comment by pourias1999** [comment]
مرسی

**Comment by pourias1999** [comment]
سلام عصرتون بخیر
فایل جدید را دانلود کردم دیتابیس هم جایگزین کردم اما hut را نمیاره!
