### ISSUE TITLE
اضافه کردن دانشگاه تبریز

### ISSUE THREAD

**Issue by sorenagithub** [soroushamdg/acd#110]
سلام و عرض ادب
لطفا lms دانشگاه تبریز رو هم اضافه کنید.
lms.tabrizu.ac.ir

**Comment by sorenagithub** [comment]
سلام . لطفا اضافه ش کنید. نیاز ضرور دارم

**Comment by sorenagithub** [comment]
یکی نیست جواب بده؟

**Comment by soroushamdg** [comment]
اضافه شد

**Comment by sorenagithub** [comment]
درود بر  شما. خیلی اقایی
