### ISSUE TITLE
چجوری کامل پاک کنیم؟ فایل هارو پاک کردم٬ولی بعد از خاموش و روشن شدن اسریشن ارور میده

### ISSUE THREAD

**Issue by madmadi7175** [soroushamdg/acd#113]

**Comment by soroushamdg** [comment]
koja error mide? windows? ye screenshoti chizi befrestid

**Comment by madmadi7175** [comment]
<a href="http://uupload.ir/view/dlnw_screenshot_(593).png" target="_blank"><img src="http://uupload.ir/files/dlnw_screenshot_(593)_thumb.png" border="0" alt="آپلود عکس" /></a><a href="http://uupload.ir/view/g184_screenshot_(592).png" target="_blank"><img src="http://uupload.ir/files/g184_screenshot_(592)_thumb.png" border="0" alt="آپلود عکس" /></a><a href="http://uupload.ir/view/s1b8_screenshot_(591).png" target="_blank"><img src="http://uupload.ir/files/s1b8_screenshot_(591)_thumb.png" border="0" alt="آپلود عکس" /></a><a href="http://uupload.ir/view/wvdq_screenshot_(590).png" target="_blank"><img src="http://uupload.ir/files/wvdq_screenshot_(590)_thumb.png" border="0" alt="آپلود عکس" /></a>

نزدیک سی تا هستن
