### ISSUE TITLE
اضافه کردن دانشگاه تحصیلات تکمیلی کرمان

### ISSUE THREAD

**Issue by alikhajehhasani** [soroushamdg/acd#118]
http://lms.kgut.ac.ir/mod/adobeconnect/view.php?id=93

**Comment by soroushamdg** [comment]
سلام نمونه لینک کلاس بفرستید

**Comment by alikhajehhasani** [comment]
http://vc.kgut.ac.ir/re5i9fuia4pl/?session=breezqpkgppz673nb8qm6

**Comment by alikhajehhasani** [comment]
http://lms.kgut.ac.ir/mod/adobeconnect/view.php?id=93 سلام این هم لینک یکی
دیگه از کلاسا

**Comment by alikhajehhasani** [comment]
http://lms.kgut.ac.ir/mod/adobeconnect/view.php?id=93

**Comment by soroushamdg** [comment]
اضافه شد
