### ISSUE TITLE
Error When Selecting acd_sengine.acde "you chose the wrong file"

### ISSUE THREAD

**Issue by skyblueplus** [soroushamdg/acd#12]
Can't get through the first dialog box.
Windows 10 x64, also checked folder permissions.

**Comment by sina-rst** [comment]
Yes I've this problem too

**Comment by soroushamdg** [comment]
i'm working on it

**Comment by soroushamdg** [comment]
@skyblueplus @sina-rst 
لطفا اخرین نسخه رو دانلود و تست کنید، احتمال زیاد مشکل یا رفع بشه یا راحت تر بشه منبعش رو پیدا کرد

**Comment by skyblueplus** [comment]
@soroushamdg 
ورژن آخر هم چک شد، متاسفانه هنوز همون مشکل پابرجاست
(نسخه های 1.0.4 تا 1.0.6 تست شدند)
