### ISSUE TITLE
issues on downloading from tehranclass

### ISSUE THREAD

**Issue by thisissinior** [soroushamdg/acd#121]
hey guys, downloading from tehranclass fails every time, every thing goes well with loging in and adding the URL to download from, but then it just said  0 file has been downloaded and extracted successfully, and it happened with every and each other URL I had added, help me please, I have a very limited time to download the videos

**Comment by soroushamdg** [comment]
سلام لینک کلاس بفرستید

**Comment by thisissinior** [comment]
> سلام لینک کلاس بفرستید

[jalase 1 amar.txt](https://github.com/soroushamdg/acd/files/4892382/jalase.1.amar.txt)

**Comment by thisissinior** [comment]
> > سلام لینک کلاس بفرستید
> 
> [jalase 1 amar.txt](https://github.com/soroushamdg/acd/files/4892382/jalase.1.amar.txt)

سلام و خسته نباشید. مشکل تهران کلاس رفع شدنی هست؟
