### ISSUE TITLE
دانشگاه هنر اصفهان

### ISSUE THREAD

**Issue by nassirihadi** [soroushamdg/acd#123]
لینک سامانه:
http://lms1.aui.ac.ir/
لینک Adobe Connect:
http://vc.aui.ac.ir/

thanks

**Comment by soroushamdg** [comment]
سلام
نمونه لینک کلاس بفرستید

**Comment by nassirihadi** [comment]
http://vc.aui.ac.ir/puc3ct7w75d5/?session=breezbreezbphktw5diqceq37v&proto=true

**Comment by nassirihadi** [comment]
?
