### ISSUE TITLE
add Urmia University

### ISSUE THREAD

**Issue by ShahoAzizi** [soroushamdg/acd#14]
plz add Urmia University (From Student Guild Council of UU)
 Link : https://urmia9.viannacloud.ir/

**Comment by soroushamdg** [comment]
لطفا یه نمونه لینک برای دیدن دوباره از کلاس های ضبط شده رو بفرستید
لینکی که داخل سامانه دانشگاهتون قرار داده شده

**Comment by shahram305** [comment]
http://195.114.4.75/phx6ojspim3a/?session=breezbreezbk2cu3t6zc87x9ra&proto=true

بفرمایید

**Comment by shahram305** [comment]
http://195.114.4.75/phx6ojspim3a/?session=breezbreezbk2cu3t6zc87x9ra&proto=true

**Comment by ShahoAzizi** [comment]
https://urmia9.viannacloud.ir/  لینک دانشگاه ارومیه

**Comment by ShahoAzizi** [comment]
البته مال ما از طریق سما وارد میشه ولی مرحله امنیتی نداره اول ائن لینک بالا ک فرستادم رو میزنی بعد با این لینک سما وارد سیستم میشه
http://sama.urmia.ac.ir/SamaSSO/Account/LogOn?ReturnUrl=%2fSamaSSO%2fOpenId%2fAskUser

**Comment by soroushamdg** [comment]
سلام
دارم روش کار میکنم، چنتا دانشگاه و موسسه دیگه هم هستن، اما ممکنه یکم طول بکشه چون خودمم یکم درگیر امتحانا و میانترمام.

**Comment by ShahoAzizi** [comment]
> سلام دارم روش کار میکنم، چنتا دانشگاه و موسسه دیگه هم هستن، اما ممکنه یکم طول بکشه چون خودمم یکم درگیر امتحانا و میانترمام.
> […](#)
> On May 10, 2020, at 6:46 AM, Shaho Azizi ***@***.***> wrote: ﻿ البته مال ما از طریق سما وارد میشه ولی مرحله امنیتی نداره اول ائن لینک بالا ک فرستادم رو میزنی بعد با این لینک سما وارد سیستم میشه http://sama.urmia.ac.ir/SamaSSO/Account/LogOn?ReturnUrl=%2fSamaSSO%2fOpenId%2fAskUser — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

دمت گرم موفق باشی

**Comment by soroushamdg** [comment]
🙏
سلام دیروز تو اخرین نسخه دانشگاه ارومیه رو گذاشتم، دانلود کردی یه تست بکن اوکی هست یا نه

**Comment by ShahoAzizi** [comment]
> 🙏
> سلام دیروز تو اخرین نسخه دانشگاه ارومیه رو گذاشتم، دانلود کردی یه تست بکن اوکی هست یا نه

عالیه...دمت گرم ظاهرا دانشگاه آدرس های دیگه ایم گذاشته 
همون آدرس قبلی فقط از 1 تا 9

https://urmia1.viannacloud.ir
تا
https://urmia9.viannacloud.ir

**Comment by ShahoAzizi** [comment]
و اینکه امتحانم کردم متاسفانع ارور میاره...اگه خودتون لینک رو بزنین وارد یه محیط میشه که از اونجا باید ورود از طریق سما رو زد که از اون صفخه جدید هستش که نام کاربری و رمز وارد میشه
 ینی این لینک پایین

http://sama.urmia.ac.ir/SamaSSO/Account/LogOn?ReturnUrl=%2fSamaSSO%2fOpenId%2fAskUser

**Comment by ShahoAzizi** [comment]
ممنون میشم اگه وقت کردین یه نگا بندازین

**Comment by ShahoAzizi** [comment]
عرض کنم که لینک سما برای همه ی ادرس های 1 تا 9 یک ادرس ثابته همون که نو کامنت قبل فرستادم...اگه وقت کردین ممنون میشم یه نگاهی بندازی

**Comment by ShahoAzizi** [comment]
ارور هم میگه دانشگاه یا یوزر و پسوردت رو چک کن

**Comment by soroushamdg** [comment]
سلام مرسی که تست کردی
من بازم چک میکنم

**Comment by ShahoAzizi** [comment]
سلام رفیق جان
اگه وقت کردی میشه یه نگاه بندازی
![SharedScreenshot](https://user-images.githubusercontent.com/20494643/86948310-9be3cd00-c155-11ea-87e4-ba6cee147503.jpg)
تو مرحله اول از اون  لینکا ک گذاشتین وارد چنین محیطی میشه ولی با این لینک نمیشه وارد اکانت کلاس مجازی شد بلکه باید ورود از طریق سامانه سما زده بشه
ورود از طریق سامانه سما ک زده بشه وارد این لینک میشه
http://sama.urmia.ac.ir/SamaSSO/Account/LogOn?ReturnUrl=%2fSamaSSO%2fOpenId%2fAskUser
و یوزر و پسورد در این لینک سامانه سما وارد میشن
اگه خواستی یوسر و پسورد سما رو میفرستم تا چکش کنی
دمت گرم
![SharedScreenshot](https://user-images.githubusercontent.com/20494643/86948688-2f1d0280-c156-11ea-8774-9e53218053cf.jpg)
