### ISSUE TITLE
اضافه کردن دانشگاه صنعتی قم

### ISSUE THREAD

**Issue by amircloner** [soroushamdg/acd#21]
salam

vc.parsianfcp.ir
vlp.parsianfcp.ir
vc.qut.ac.ir

**Comment by amircloner** [comment]
فقط برای ما برای مشاهده ویدیو های نیازی به رمز عبور نداریم

**Comment by soroushamdg** [comment]
لطفا یه نمونه لینکی که داخل lms دانشگاهتون میزارن رو بفرستید
