### ISSUE TITLE
adding http://live.ganjedu.ir/

### ISSUE THREAD

**Issue by mohammadekramian** [soroushamdg/acd#27]
Hello
please add this school
http://live.ganjedu.ir/
Thank you so much

**Comment by soroushamdg** [comment]
سلام لطفا 1-لینک
lms
که از داخل اون لاگین میکنید و لینک کلاس ها براتون قرار داده میشه و 2- یه نمونه لینک از یکی از کلاس هاتون رو بفرستید

**Comment by mohammadekramian** [comment]
1- http://live.ganjedu.ir/grammar
2- http://live.ganjedu.ir/p8z4imdzd899/

**Comment by mohammadekramian** [comment]
سلام 1- http://live.ganjedu.ir/grammar
2- Adobe Connect Central Login

| 
| 
|  | 
Adobe Connect Central Login


 |

 |

 |





    On Saturday, May 23, 2020, 12:33:10 AM GMT+4:30, Soroush M Pour <notifications@github.com> wrote:  
 
 


سلام لطفا 1-لینک
lms
که از داخل اون لاگین میکنید و لینک کلاس ها براتون قرار داده میشه و 2- یه نمونه لینک از یکی از کلاس هاتون رو بفرستید

**Comment by soroushamdg** [comment]
سلام، مرسی، بررسی میکنم

**Comment by mohammadekramian** [comment]
ممنون از لطفتون
    On Saturday, May 23, 2020, 05:43:49 PM GMT+4:30, Soroush M Pour <notifications@github.com> wrote:  
 
 


سلام، مرسی، بررسی میکنم

**Comment by mohammadekramian** [comment]
داداش تا یه هفته اینده لینکارو میبندن، میشه لطف کنی و زودتر ادد کنی؟


Sent from Yahoo Mail for iPhone


On Saturday, May 23, 2020, 6:11 pm, M E <fb.me70@yahoo.com> wrote:

 ممنون از لطفتون
    On Saturday, May 23, 2020, 05:43:49 PM GMT+4:30, Soroush M Pour <notifications@github.com> wrote:  
 
 


سلام، مرسی، بررسی میکنم

**Comment by mohammadekramian** [comment]
حاجی چی شد پس؟

**Comment by soroushamdg** [comment]
لطفا نسخه اخر رو دانلود کنید
اگر کار نکرد به آی دی تو توضیحات این چنل پیام بدید:
@iranpythoneers
