### ISSUE TITLE
مدرسان شریف

### ISSUE THREAD

**Issue by saraaskari** [soroushamdg/acd#29]
http://vc.modaresanesharif.ac.ir/

**Comment by soroushamdg** [comment]
سلام لطفا 1-لینک 
lms 
 که از داخل اون لاگین میکنید و لینک کلاس ها براتون قرار داده میشه و 2- یه نمونه لینک از یکی از کلاس هاتون رو بفرستید

**Comment by saraaskari** [comment]
سلام شبتون بخیر و ممنون از سایت خوبتون
http://vc.modaresanesharif.ac.ir/pl23415mvwii/  این لینک یکی از جلسات هست
http://vc.modaresanesharif.ac.ir/admin/home/homepage?account-id=7&principal-id=1484780&showNotif=true&OWASP_CSRFTOKEN=f08c41c5ad5322aec9bab984aa65db66414d744e8c10962cfde83bcfc33ff43f
این هم لینک پیج که وارد شدم
http://vc.modaresanesharif.ac.ir این هم لینک ورودش برای وارد کردن یوزر و
پسورد هست
vc.

**Comment by soroushamdg** [comment]
مرسی، بررسی میکنم

**Comment by saraaskari** [comment]
سلام اکی نمیشه به نظرتون ؟

**Comment by soroushamdg** [comment]
لطفا نسخه اخر رو دانلود کنید
اگر کار نکرد به آی دی تو توضیحات این چنل پیام بدید:
@iranpythoneers
