### ISSUE TITLE
معماری معاصر

### ISSUE THREAD

**Issue by eza19910518** [soroushamdg/acd#30]

**Comment by eza19910518** [comment]
https://lms8.uok.ac.ir/HomePage.aspx

https://lms8.uok.ac.ir/Lesson/MjQ=/OTM1Ng==/Mw==/OTM1Ng==/OTM1Ng==

vc5.uok.ac.ir/l5hsm0xt5pp/?launcher=false&fcsContent=true&pbMode=normal

سلام ممنون میشم این رو با اسم معماری معاصر اد کنید

**Comment by soroushamdg** [comment]
سلام، دانشگاه کردستان به نرم افزار اضافه شده قبلا، همون لیست لینک هارو یکم بگردید پیدا میشه

**Comment by soroushamdg** [comment]
لطفا نسخه اخر رو دانلود کنید
اگر کار نکرد به آی دی تو توضیحات این چنل پیام بدید:
@iranpythoneers
