### ISSUE TITLE
سلام، دانشگاه کردستان به نرم افزار اضافه شده قبلا، همون لیست لینک هارو یکم بگردید پیدا میشه

### ISSUE THREAD

**Issue by eza19910518** [soroushamdg/acd#31]
سلام، دانشگاه کردستان به نرم افزار اضافه شده قبلا، همون لیست لینک هارو یکم بگردید پیدا میشه

> On May 23, 2020, at 5:23 PM, eza19910518 <notifications@github.com> wrote:
> 
> ﻿
> https://lms8.uok.ac.ir/HomePage.aspx
> 
> https://lms8.uok.ac.ir/Lesson/MjQ=/OTM1Ng==/Mw==/OTM1Ng==/OTM1Ng==
> 
> vc5.uok.ac.ir/l5hsm0xt5pp/?launcher=false&fcsContent=true&pbMode=normal
> 
> سلام ممنون میشم این رو با اسم معماری معاصر اد کنید
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

_Originally posted by @soroushamdg in https://github.com/soroushamdg/acd/issues/30#issuecomment-633048130_

**Comment by eza19910518** [comment]
ببخشید من لینک بالای صفحه اجرای کلاس رو وارد میکنم
میگه که 
invalid link 
مشکل از لینکی که من وارد میکنم هست یا کلا اجازه دسترسی نداریم؟

**Comment by soroushamdg** [comment]
اگه مشکل از لینکه پس لطفا بی زحمت یه نمونه لینک که داخل 
lms 
هستش رو بفرستید(دقت کنید اگر روی لینک کلیک کنید، لینک عوض میشه) پس دقیقا همون لینکی که داخل 
lms 
هست رو نیاز داریم.

**Comment by eza19910518** [comment]
ببخشید لینکی که بالای سر برگ صفحه فایلهای ضبط شده کلاس هست رو بفرستم؟
یا کلیک راست کنم روی یکی از فایلهای ضبط شدهو اون لینک رو کپی کنم و بفرستم؟
و برای هر کلاس جداگانه این کار رو بکنم ؟
چون در مورد همه کلاسها لینک در دسترس نیست
و اینکه با دادن یه نمونه لینک همه فایلهای اون کلاس قابل دسترسی میشه؟
ببخشید همه سوالامو یه جا پرسیدم

**Comment by soroushamdg** [comment]
کلیک راست کنید روی لینک یکی از کلاس ها کپی کنید و اون رو بفرستید

الان فقط یدونه از لینک هارو اینجا بفرستید تا من مشکل دانشگاه شما رو حل کنم

بعدا که خواستید دانلود کنید، باید لینک تک تک کلاس هارو به نرم افزار بدید

**Comment by eza19910518** [comment]
https://lms8.uok.ac.ir/Lesson/MjQ=/OTM1Ng==/Mw==/OTM1Ng==/OTM1Ng==

خیلی ممنون

**Comment by eza19910518** [comment]
لینک سر برگ کلاس
https://lms8.uok.ac.ir/VirtualAdmin/MjQ=/OTM1Ng==/Mw==/OTM1Ng==

 لینک فایل خود کلاس که فایل ضبط شده داخلشه 
vc5.uok.ac.ir/l59n3za3kpn/?launcher=false&fcsContent=true&pbMode=normal

**Comment by soroushamdg** [comment]
سلام،لینک شمارو چک کردم، بنظر میاد درست کار میکنه

**Comment by soroushamdg** [comment]
لطفا نسخه اخر رو دانلود کنید
اگر کار نکرد به آی دی تو توضیحات این چنل پیام بدید:
@iranpythoneers
