### ISSUE TITLE
پیام نور

### ISSUE THREAD

**Issue by s-alirezam** [soroushamdg/acd#32]
لطفا پیام نور تهران شمال اضافه کنید
lms1.tpnu.ac.ir
لینک یکی از کلاسها:
http://vc.tpnu.ac.ir/p2x24n2niu1v/?OWASP_CSRFTOKEN=ef020892038b50cc97c7b34207e104284f098d168f2cd5700c7f5fe518caa5e5&proto=true

**Comment by soroushamdg** [comment]
سلام، پیام نور قبلا اضافه شده و لینکش رو هم تست کردم درست کار میکنه

**Comment by soroushamdg** [comment]
لطفا نسخه اخر رو دانلود کنید
اگر کار نکرد به آی دی تو توضیحات این چنل پیام بدید:
@iranpythoneers

**Comment by MMR1400** [comment]
> لطفا نسخه اخر رو دانلود کنید
> اگر کار نکرد به آی دی تو توضیحات این چنل پیام بدید:
> @iranpythoneers

لطفا پیام نور مشهد رو اضافه کنید
http://lms.razavi.pnu.ac.ir/
