### ISSUE TITLE
موسسه دهخدا قزوین

### ISSUE THREAD

**Issue by 9713623** [soroushamdg/acd#33]
http://adi.tehranlms.ir/login/index.php
سلام لطفا این لینک رو اضافه کنید

**Comment by 9713623** [comment]
http://adi.tehranlms.ir/login/index.php
سلام لطفا این لینک رو اضافه کنید

**Comment by soroushamdg** [comment]
لطفا نسخه اخر رو دانلود کنید
اگر کار نکرد به آی دی تو توضیحات این چنل پیام بدید:
@iranpythoneers

**Comment by 9713623** [comment]
کار نمیکنه ارور میده

**Comment by Mohammad9363** [comment]
این دانشگاه رو هم اضافه کنید
https://lms.ilam.ac.ir
