### ISSUE TITLE
مشکل نصب ورژن 1.1.0

### ISSUE THREAD

**Issue by mohammadekramian** [soroushamdg/acd#34]
سلام. ورزن اخر روی سیستمم نصب نمیشه. موقعی که فایل دیتابیس رو لود میکنم اررور میده
You've selected wrong file

**Comment by soroushamdg** [comment]
لطفا نسخه اخر رو دانلود کنید
اگر کار نکرد به آی دی تو توضیحات این چنل پیام بدید:
@iranpythoneers

**Comment by mohammadekramian** [comment]
ممنونم
