### ISSUE TITLE
سلام دانشگاه آزاد خرم آباد رو بذاريد

### ISSUE THREAD

**Issue by emir627** [soroushamdg/acd#36]
دانشگاه آزاد خرم اباد👇
edu.khoiau.ac.ir
 👆لينكش

**Comment by soroushamdg** [comment]
سلام
لطفا نمونه لینک کلاس بفرستید
لینکی که داخل
lms
قرار داده شده رو بفرستید لطفا
یعنی روی یکی از لینک ها کلیک راست کنید و کپی لینک رو بزنید
