### ISSUE TITLE
NEW SCHOOL

### ISSUE THREAD

**Issue by mahdihmzd** [soroushamdg/acd#38]
لینک سایت
https://lms.roshdiyeh.ac.ir/mod/adobeconnect/view.php?id=130

لینک یکی از جلسه ها
http://37.152.176.36/pdi225pth0se/?session=breezbreezt6dqmr89tpfbd3ux&html-view=false&proto=true

**Comment by soroushamdg** [comment]
لینکی که داخل 
lms 
قرار داده شده رو بفرستید لطفا
یعنی روی یکی از لینک ها کلیک راست کنید و کپی لینک رو بزنید
