### ISSUE TITLE
#request scool Mazust

### ISSUE THREAD

**Issue by ehsauni** [soroushamdg/acd#389]
سلام دوست عزیز وقتتون بخیر
خیلی ممنونم از زحماتتون و کمال تشکر رو خدمتتون دارم
من یک مشکلی دارم فایل های کلاس مجازی دانشگاه رو نتونستم دانلود کنم
reg.mazust.ac.ir
https://vee2.mazust.ac.ir/ppzkoj17weqr?session=breeznkssz3hbxzu8wx5u&proto=true
vee2.mazust.ac.ir
که وقتی وارد صف میکنم ارور failed to download نمایش داده میشه
معذرت میخوام از اینکه وقتتون رو گرفتم.

**Comment by soroushamdg** [comment]
سلام، وقت شما هم بخیر، لینک شما مشکل داره، لینک درستش اینه:
https://vee2.mazust.ac.ir/ppzkoj17weqr/?session=breeznkssz3hbxzu8wx5u&proto=true

قبل از ?session
یه /
باید باشه مثل لینک بالا.

**Comment by ehsauni** [comment]
بازم نمایش داده میشه . یعنی ممکنه مشکل از سایت باشه ؟ failed to download خیلی ممنون از توجهتون اما بازم مشکل حل نشد و پیغام
