### ISSUE TITLE
اجرا نشدن برنامه

### ISSUE THREAD

**Issue by MasoudHeydari** [soroushamdg/acd#391]
سلام و وقت بخیر
من برنامه رو دانلود کردم و از حالت فشرده خارج کردم و وقتی اجراش میکنم اصلا اجرا نیمشه
تو تسک منیجر که نگاه کردم جزو برنامه های پس زمینه بود ولی اجرا نمیشد!
مرسی

**Comment by soroushamdg** [comment]
سلام وقت بخیر
نرم افزار طول میکشه یکم تا اجرا بشه، یکم صبر کنید اوکی میشه
اگر اروری داشته باشه ارور رو نشون میده 99%

**Comment by hasanaaaaa** [comment]
با سلام
من هم همین مشکل رو دارم و بعد از یک مدت طولانی eror میده. failed-to-execute-script-main

**Comment by soroushamdg** [comment]
برید داخل آدرس زیر
C:\Users\{username}\AppData\Local\Temp\ACDTEMP
و فایل log.log
رو اینجا اتچ کنید

**Comment by MasoudHeydari** [comment]
برای من این فایل خالیه!

**Comment by hasanaaaaa** [comment]
[log.log](https://github.com/soroushamdg/acd/files/5624634/log.log)
داحل لب تاب این فایل بدون متن هستش اما در کامپیوترم  دارای متنه که براتون فایل متن دار رو اتچ کردم.

**Comment by soroushamdg** [comment]
@hasanaaaaa 
برید داخل این سایت
https://shecan.ir
و یدور با این dns
امتحان کنید

**Comment by soroushamdg** [comment]
> برای من این فایل خالیه!

شما منتظر موندید؟ هیچ اروری نداد؟

**Comment by MasoudHeydari** [comment]
> > برای من این فایل خالیه!
> 
> شما منتظر موندید؟ هیچ اروری نداد؟

بله، هم کامپیوتر و هم لپ تاپ، منم با شکن امتحان میکنم ببینم چی میشه!

**Comment by hasanaaaaa** [comment]
درست شد. خیلی ممنون جناب مهندس.

**Comment by hasanaaaaa** [comment]
با اینکه استاد اسکرین خودشون رو
 share 
کردن ولی تصویر دانلود نمیشه و فقط صدا دانلود میشه
