### ISSUE TITLE
New school

### ISSUE THREAD

**Issue by Mohammad9363** [soroushamdg/acd#40]
Please add ILAM University Thanks.
https://lms.ilam.ac.ir

**Comment by chalak13** [comment]
http://elm3.ir/

**Comment by chalak13** [comment]
Please add http://elm3.ir/ Thanks.

**Comment by soroushamdg** [comment]
لینکی که داخل
lms
قرار داده شده رو بفرستید لطفا
یعنی روی یکی از لینک ها کلیک راست کنید و کپی لینک رو بزنید

**Comment by Mohammad9363** [comment]
با سلام
این لینک درس دینامیک ماشینه که داخل سامانه lms هست امیدوارم منظورتون همین
بوده باشه.
http://vc.ilam.ac.ir/pf49isf3xc4z/

**Comment by soroushamdg** [comment]
سلام، اضافه شد، لطفا اخرین نسخه رو دانلود کنید
https://github.com/soroushamdg/acd/releases/tag/v1.2.1

**Comment by Mohammad9363** [comment]
> 
> 
> سلام، اضافه شد، لطفا اخرین نسخه رو دانلود کنید
> https://github.com/soroushamdg/acd/releases/tag/v1.2.1

با سلام
ACD luncher مشکل داره 
همین که run میکنم پنجره cmd باز میشه برنامه نویسی رو اجرا میکنه و بسته میشه چند بار هم دانلود کردم ولی بازم حل نشد

**Comment by soroushamdg** [comment]
اخرین نسخه گوگل کروم رو دارید رو سیستم؟

**Comment by Mohammad9363** [comment]
> 
> اخرین نسخه گوگل کروم رو دارید رو سیستم؟
> […](#)
> On Jun 6, 2020, at 1:40 PM, Mohammad9363 ***@***.***> wrote: ﻿ سلام، اضافه شد، لطفا اخرین نسخه رو دانلود کنید https://github.com/soroushamdg/acd/releases/tag/v1.2.1 با سلام ACD luncher مشکل داره همین که run میکنم پنجره cmd باز میشه برنامه نویسی رو اجرا میکنه و بسته میشه چند بار هم دانلود کردم ولی بازم حل نشد — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

سلام کروم رو به آخرین ورژن ارتقا دادم بازم مشکل رفع نشد

**Comment by Mohammad9363** [comment]
> 
> 
> > اخرین نسخه گوگل کروم رو دارید رو سیستم؟
> > […](#)
> > On Jun 6, 2020, at 1:40 PM, Mohammad9363 _**@**_.***> wrote: ﻿ سلام، اضافه شد، لطفا اخرین نسخه رو دانلود کنید https://github.com/soroushamdg/acd/releases/tag/v1.2.1 با سلام ACD luncher مشکل داره همین که run میکنم پنجره cmd باز میشه برنامه نویسی رو اجرا میکنه و بسته میشه چند بار هم دانلود کردم ولی بازم حل نشد — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> سلام کروم رو به آخرین ورژن ارتقا دادم بازم مشکل رفع نشد

ACD لانچر رو اجرا میکنم پنجره cmd باز میشه برنامه نویسی رو اکسترک میکنه و بسته میشه و فایل export رو ایجاد میکنه

**Comment by soroushamdg** [comment]
لطفا از صفحه فیلم بگیرید و به ایدی که داخل چنل زیر هست بفرستید: 
@iranpythoneers
