### ISSUE TITLE
درخواست اضافه کردن دانشگاه علمی-کاربردی

### ISSUE THREAD

**Issue by mbm13781221** [soroushamdg/acd#43]
http://lms.azuast.com

**Comment by soroushamdg** [comment]
نمونه لینک کلاس بفرستید
لینکی که داخل
lms
قرار داده شده رو بفرستید لطفا
یعنی روی یکی از لینک ها کلیک راست کنید و کپی لینک رو بزنید

**Comment by mbm13781221** [comment]
سلام
http://vc.azuast.com/rw8a361kqfhm/?session=breezspn6i4uyz7iw74xh

**Comment by mbm13781221** [comment]
سلام.
در گیت هاب فرستاده شد.

**Comment by soroushamdg** [comment]
سلام، اضافه شد، لطفا اخرین نسخه رو دانلود کنید
https://github.com/soroushamdg/acd/releases/tag/v1.2.1

**Comment by mbm13781221** [comment]
سلام، ممنون🙏

**Comment by sadegh-golzari** [comment]
سلام اگه امکان داره داشگاه من هم اضافه کنید
http://elc2.sadjad.ac.ir/sadjad73NLQNQDFPZH50BA9

**Comment by sadegh-golzari** [comment]
دانشگاه غیر انتفایی سجاد مشهد
