### ISSUE TITLE
درخواست اضافه کردن آدرس جدید

### ISSUE THREAD

**Issue by reza2398** [soroushamdg/acd#44]
http://lms.agah.com
.سلام.ممنون میشم این لینک رو اد کنین

**Comment by soroushamdg** [comment]
نمونه لینک کلاس بفرستید
لینکی که داخل
lms
قرار داده شده رو بفرستید لطفا
یعنی روی یکی از لینک ها کلیک راست کنید و کپی لینک رو بزنید

**Comment by reza2398** [comment]
vc.agah.com/l2ie1lph7ej/?launcher=false&fcsContent=true&pbMode=normal

درسته؟
