### ISSUE TITLE
دانشگاه پیام نور مرکز مشهد به لیست اضافه شود

### ISSUE THREAD

**Issue by MMR1400** [soroushamdg/acd#46]
http://lms.razavi.pnu.ac.ir/

**Comment by soroushamdg** [comment]
نمونه لینک کلاس بفرستید
لینکی که داخل
lms
قرار داده شده رو بفرستید لطفا
یعنی روی یکی از لینک ها کلیک راست کنید و کپی لینک رو بزنید

**Comment by MMR1400** [comment]
سلام
این لینک رو که میزنم ادوبی باز میشه
http://yar1.meetingyar.com/pt7ms53bwy6b/?session=breezmf5obr2x5swoutdy

**Comment by MMR1400** [comment]
این لینک صفحه ای هست که جلسه کلاس در اون هست
http://87.236.215.223/mod/adobeconnect/view.php?id=74211

**Comment by soroushamdg** [comment]
اضافه شد
