### ISSUE TITLE
new school

### ISSUE THREAD

**Issue by mohammadamin-s-b** [soroushamdg/acd#48]
https://class3.cafetadris.com/

**Comment by soroushamdg** [comment]
نمونه لینک کلاس بفرستید
لینکی که داخل
lms
قرار داده شده رو بفرستید لطفا
یعنی روی یکی از لینک ها کلیک راست کنید و کپی لینک رو بزنید

**Comment by mohammadamin-s-b** [comment]
https://class3.cafetadris.com/iedep2661?proto=true

**Comment by soroushamdg** [comment]
داخل خود سایت اصلی اول لاگین میکنید که به کلاسا دسترسی داشته باشید؟
یا اینکه داخل 
class3.cafetadris.com 
مستقیما لاگین میشید؟

**Comment by mohammadamin-s-b** [comment]
https://cafetadris.com/dashboard/enrolls
داخل این لاگین میشم

**Comment by soroushamdg** [comment]
سلام، اضافه شد، لطفا اخرین نسخه رو دانلود کنید
https://github.com/soroushamdg/acd/releases/tag/v1.2.1

**Comment by soroushamdg** [comment]
سلام، اضافه شد، لطفا اخرین نسخه رو دانلود کنید
https://github.com/soroushamdg/acd/releases/tag/v1.2.1

**Comment by soroushamdg** [comment]
احتمالا سرور هاشون بلاک میکنند
چندبار امتحان کنید احتمالا بشه
چون موقع اضافه کردن تست کردم
