### ISSUE TITLE
دیتای جدید رو چطور کپی کنیم؟

### ISSUE THREAD

**Issue by MMR1400** [soroushamdg/acd#49]
https://github.com/soroushamdg/acd/blob/c8dde548122e85b9f79ed4ec1709aa4f69c6167f/latest_database_and_engine/database.acddb#L1

**Comment by soroushamdg** [comment]
https://github.com/soroushamdg/acd/releases/tag/v1.2.1
از اینجا اخرین نسخه رو دانلود کنید و روی فایل های قبلی کپی و
replace
کنید
