### ISSUE TITLE
دانشگاه دولتی بیرجند اضافه شود

### ISSUE THREAD

**Issue by aref8300** [soroushamdg/acd#50]
lms.birjand.ac.ir
vc.birjand.ac.ir

**Comment by soroushamdg** [comment]
سلام
لطفا نمونه لینک از کلاس هاتون رو هم بفرستید

**Comment by aref8300** [comment]
http://vc.birjand.ac.ir/pyph9pziiqok/?session=breezbreezqsp4noq835uh33cw&proto=true

**Comment by soroushamdg** [comment]
اضافه شد
