### ISSUE TITLE
اضافه کردن لینک سرور کلاس زبان آفرینش

### ISSUE THREAD

**Issue by ParhamGhafouri** [soroushamdg/acd#51]
با سلام، ممنون می شوم اگر لینک مربوط به سرور کلاس زبان آفرینش با لینک زیر را اضافه بفرمایید :

http://connect3.afarinesh.org/

نمونه لینک های دانلود 

http://connect3.afarinesh.org/pvrjn45nf8um?proto=true&launcher=true&session=breezr3yub9fiqtrw3t6n

**Comment by arashmad** [comment]
Could you download via this software? I'm trying to download from Afarinesh, too. But it no use! My video link starts with _connect9_.
