### ISSUE TITLE
New school

### ISSUE THREAD

**Issue by AliKhanHastam** [soroushamdg/acd#53]
Please add Shamsipour university.

https://shamswebinar.ir/p40itk8pg2u5/?OWASP_CSRFTOKEN=f07cf5307bea8bd61aab199d6c19cce6b7f50a2a65e162826d60deb34552b146

Thanks!

**Comment by soroushamdg** [comment]
سلام
لطفا لینک سایت موسسه یا دانشگاه و لینک پنلی که کلاس هاتون داخل قرار داده شده رو هم بفرستید

**Comment by ahpna** [comment]
ببخشید دانشگاه شیراز هم هست؟
اگه نیست میشه اضافه کنید؟

**Comment by soroushamdg** [comment]
اضافه شد

**Comment by ahpna** [comment]
سلام
خسته نباشید
ببخشید ولی دانشگاه شیراز نیست
فکر کنم به جای اون دانشگاه صنعتی شیراز رو اضافه کردید
لینک کلاس های دانشگاه شیراز رو نمیدونم چجوری باید پیدا کنم ولی مثلا یکی از
کلاساموت اولش ادرسش این بود http://vc69.shirazu.ac.ir/ یا یکی دیگه این بود
http://vc23.shirazu.ac.ir/
امکانش هست این دانشگاه هم اضافه بشه و اگه شده چجوری میتونم دسترسی داشته
باشم؟

**Comment by Amir313-12** [comment]
لطفا دانشگاه محقق اردبیلی رو هم اضافه کنید 
http://45.82.136.223/moodle/
https://uma.ac.ir
