### ISSUE TITLE
دانشگاه

### ISSUE THREAD

**Issue by pouyahbt** [soroushamdg/acd#54]
سلام لطفا دانشگاه صنعتی قوچان رو هم اضافه کنید(qiet.ac.ir)

**Comment by soroushamdg** [comment]
سلام
لطفا لینک سایت موسسه یا دانشگاه و لینک پنلی که کلاس هاتون داخل قرار داده شده و یه نمونه لینک از کلاس هاتون رو هم بفرستید

**Comment by pouyahbt** [comment]
قابل توجه دانشجویان عزیز؛

دانشجویان عزیز جهت ورود به کلاس باید از طریق لینک زیر وارد شوند:
https://webinar2.qiet.ac.ir/rwphox76tdsx/

کلاس ماشین 1 هر هفته دو جلسه یک ساعته برگزار می شود. جلسه اول، روز دوشنبه ساعت 12:30 و جلسه دوم روز چهارشنبه ساعت 12:30 برگزار می شود.

همچنین، جلسات کلاس های برگزار شده در سامانه وبینار، ضبط شده و از طریق لینک های زیر قابل بازبینی می باشند.

جلسه اول:
https://webinar2.qiet.ac.ir/pj88kzm6tiwq/

جلسه دوم: 
https://webinar2.qiet.ac.ir/pef3du72r4wb/

جلسه سوم:
https://webinar2.qiet.ac.ir/p2s2oq3whah1/

جلسه چهارم:
https://webinar2.qiet.ac.ir/p5xlu5p20h7y/

جلسه پنجم:
https://webinar2.qiet.ac.ir/pr8d9dmw29ut/

جلسه ششم:
https://webinar2.qiet.ac.ir/pvo1fwcx72jf/

جلسه هفتم:
https://webinar2.qiet.ac.ir/pax3a5m1hevm/

جلسه هشتم:
https://webinar2.qiet.ac.ir/p7eow26vgp23/

جلسه نهم:
https://webinar2.qiet.ac.ir/pzxjgr7lm4q4/

جلسه دهم:
https://webinar2.qiet.ac.ir/p7e7la30tzvr/

جلسه یازدهم:
https://webinar2.qiet.ac.ir/py8whshdmctd/

**Comment by pouyahbt** [comment]
این هم لینک سامانه آفلاین که فایل هاشون بارگذاری میکنن https://elc.qiet.ac.ir/

**Comment by pouyahbt** [comment]
https://qiet.ac.ir/fa
