### ISSUE TITLE
دانشگاه

### ISSUE THREAD

**Issue by saberrezaei** [soroushamdg/acd#55]
http://79.143.84.147/p6730ikb42n3

**Comment by saberrezaei** [comment]
سلام ممنون میشم این لینک اد  کنید 
ممنون از برنامه خوبتون

**Comment by soroushamdg** [comment]
سلام
لطفا لینک سایت موسسه یا دانشگاه و لینک پنلی که کلاس هاتون داخل قرار داده شده رو هم بفرستید
