### ISSUE TITLE
افزودن دانشگاه سجاد مشهد

### ISSUE THREAD

**Issue by b0z0rgmehr** [soroushamdg/acd#56]
سلام
لطفا در صورت امکان دانشگاه صنعتی سجاد مشهد رو اضافه کنید

سایت دانشگاه
https://sadjad.ac.ir/

پورتال دانشجویی
https://pooya.sadjad.ac.ir/

مثال لینک کلاس های آنلاین
http://vlc.dpm.ir/py7o10qq59zp/

فقط بعد از ورود به لینک کلاس های آنلاین با نام کاربری و کلمه عبور,یک کلمه عبور دیگه هم در مرحله بعد باید وارد بشه تا بتونیم کلاس های ضبط شده رو مشاهده کنیم.

باتشکر

**Comment by soroushamdg** [comment]
مرحله دوم دوباره هم باید نام کاربرری هم رمز عبور وارد کنید؟
یا فقط رمز عبور؟

**Comment by b0z0rgmehr** [comment]
> مرحله دوم دوباره هم باید نام کاربرری هم رمز عبور وارد کنید؟
> یا فقط رمز عبور؟

خیر
مرحله دوم یک رمز جدا از نام کاربری و کلمه عبور هست که روزانه داخل پورتال نشون داده میشه.
