### ISSUE TITLE
سلام لطفا لینک های زیر را اضافه کنید 

### ISSUE THREAD

**Issue by saeedvanoni** [soroushamdg/acd#58]
http://live2.tehranclass.ir/pjqd2kq9f2qw/
با لینک بالا درس های ضبط شده را میبینیم
پسورد : fundgrm 
وبا لینک پایین به صورت آنلاین کانکت میشیم
http://live2.tehranclass.ir/geramimabani9701/

درضمن داخل نرم افزار قسمتی از من 
user name:  ؟
password:   ؟

 لطفا برای من بزارید

تشکر

**Comment by soroushamdg** [comment]
داخل قسمت یوزرنیم پسورد هرکدوم که لازم نیست داخل وبسایت یه چیز الکی بنویسید
