### ISSUE TITLE
 اضافه شدن موسسه آموزشی ماهان به نرم افزار ، با تشکر (http://www.portal.mahan.ac.ir/)

### ISSUE THREAD

**Issue by hoora24** [soroushamdg/acd#59]
http://www.portal.mahan.ac.ir/

نمونه لینک کلاس :
http://91.99.99.210:5050/p8qey9cb1di/?launcher=false&fcsContent=true&pbMode=normal

**Comment by hoora24** [comment]
سلام ، ممنون از اضافه شدن لینک ، اما هیچ جوره دیتابیس جدید دانلود نمیشه!!!!!!! اصلا لینکی برای دانلود نداره ، فقط کد فایل رو نشون میده ، چیکار باید بکنم؟

**Comment by soroushamdg** [comment]
سلام، میتونین فایل رو باز کنید و 
save as 
رو بزنید
الان اخرین نسخه کنارش فایل دیتابیس هم قرار داده شده
