### ISSUE TITLE
درخواست برای دانشگاه سجاد مشهد

### ISSUE THREAD

**Issue by AliSaZa98** [soroushamdg/acd#6]
login page :https://pooya.sadjad.ac.ir/gateway/PuyaAuthenticate.php
link address: http://elc.sadjad.ac.ir/pm98z9nw935x/

**Comment by soroushamdg** [comment]
سلام، بخاطر فیلد کد امنیتی که داخل سایت هستش، امکان اینکه نرم افزار به سیستم وارد بشه وجود نداره، در آینده اگر راهی پیدا کردم، خبرتون میکنم
