### ISSUE TITLE
http://oc3.ictsara.com/pvbgqz9lqydb/?proto=true

### ISSUE THREAD

**Issue by eshraghi121988** [soroushamdg/acd#65]
http://oc3.ictsara.com/pvbgqz9lqydb/?proto=true

**Comment by soroushamdg** [comment]
لینک پنل lms
که لینک کلاس های ضبط شده داخلش هست رو بفرستید

**Comment by eshraghi121988** [comment]
https://ictsara.com/index.php/%D8%AF%D8%B1%D9%88%D8%B3-%D9%85%D9%86
