### ISSUE TITLE
اضافه نمودن دوره دکتری دانشگاه تهران

### ISSUE THREAD

**Issue by kkamjou** [soroushamdg/acd#66]
صفحه ورودی:
http://class1.ondemy.ir/digital3
نمونه صفحه ویدیو:
http://class1.ondemy.ir/pxswmrrruilh/

**Comment by kkamjou** [comment]
درود
امکان داره بفرمایید کی اضافه می کنید؟
سپاس

**Comment by kkamjou** [comment]
کماکان منتظر پاسخ هستم.

**Comment by soroushamdg** [comment]
اضافه شد
