### ISSUE TITLE
درخواست اضافه شدن دانشگاه یزد

### ISSUE THREAD

**Issue by sahrayi** [soroushamdg/acd#70]
سلام.

لطفا در صورت امکان دانشگاه یزد رو هم اضافه کنید.
صفحه لیست کلاسها:
http://vu.yazd.ac.ir/vu/meeting.list.php
نمونه صفحه دانلود:
http://record.yazd.ac.ir/records/vc3/?sco-id=2133138&url=pm50qsvp502m

تشکر

**Comment by sahrayi** [comment]
کاش امکان اضافه‌کردن دستی لینک‌ها به لیست و ویرایش رو هم فراهم می‌کردید.

**Comment by soroushamdg** [comment]
سلام، لطف کن به آیدی زیر پیام بده:
[@thisshipistakingmefaraway](http://t.me/thisshipistakingmefaraway)
