### ISSUE TITLE
reqeust school

### ISSUE THREAD

**Issue by bfndez** [soroushamdg/acd#73]
www.lms.agah.com

**Comment by bfndez** [comment]
http://vc.agah.com/l9osrqwob32/?session=vcbreez3nb8xe6kxqgeivk5&proto=true

**Comment by arashir48** [comment]
http://vlc.rayanclass.com/

**Comment by soroushamdg** [comment]
لینک lms 
کار نمیکنه، یدور چک کنین

**Comment by bfndez** [comment]
دقیقا کدوم لینک رو باید برای شما ارسال کنیم؟؟

**Comment by bfndez** [comment]
????

**Comment by arashir48** [comment]
سلام . لطفا

http://vlc.rayanclass.com
