### ISSUE TITLE
0 course(s) download and extracting finished

### ISSUE THREAD

**Issue by reza-naderi** [soroushamdg/acd#75]
با سلام
دو بار مراحل رو از صفر انجام دادم. تمام مراحل انجام شد و یوزر پسوورد همم پذیرفته شد. اما هیچ فایلی دانلود نمیشه و پیام زیر رو میده:
0 course(s) download and extracting finished
لینک هم طبق فرمت درسته، مثلا: http://vc26.sbu.ac.ir/peex0cffjycr
هیچ فولدری دراخل فولدر export  ایجاد نمیشه

**Comment by soroushamdg** [comment]
سلام، متاسفانه شهید بهشتی لینک هاشو عوض کرده بهم ریخته
لطف کن به آیدی زیر پیام بده:
[@thisshipistakingmefaraway](http://t.me/thisshipistakingmefaraway)
