### ISSUE TITLE
دانشگاه تبریز

### ISSUE THREAD

**Issue by farzin71** [soroushamdg/acd#77]
http://vc1.tabrizu.ac.ir/pi60z49b0rmh/?session=breezbreezonkdo996auevkv89&proto=true

**Comment by soroushamdg** [comment]
لینک lms
بفرستید

**Comment by farzin71** [comment]
> لینک lms
> بفرستید

https://lms6.tabrizu.ac.ir/VirtualAdmin/MjQ=/MzA0Mg==/Mw==/MzA0Mg==
