### ISSUE TITLE
فلات قاره

### ISSUE THREAD

**Issue by rsheikhyy** [soroushamdg/acd#79]
https://learn.falatghareh.ir/ph1rqvwy8xkp/
https://learn.falatghareh.ir/pv54ziqiu9wc/
https://learn.falatghareh.ir/pny37yeiehe0/
https://learn.falatghareh.ir/podu7m3gkon8/
https://learn.falatghareh.ir/pl6j04rzwz3l/
https://learn.falatghareh.ir/pxxzpwtiklsq/

**Comment by hosseinmoradi79** [comment]
سلام میشه دانشگاه سمنان رو هم اضافه کنید
vc.semnan.ac.ir
http://vc.Semnan.ac.ir/pd1e918e65nu

**Comment by soroushamdg** [comment]
اضافه شد
