### ISSUE TITLE
اضاف کردن دانشگاه سمنان

### ISSUE THREAD

**Issue by hosseinmoradi79** [soroushamdg/acd#85]
سلام میشه دانشگاه سمنان رو اضافه کنید با تشکر
vc4.semnan.ac.ir
http://vc4.Semnan.ac.ir/pd1e918e65nu/
srm.semnan.ac.ir

**Comment by soroushamdg** [comment]
اضافه شد

**Comment by hosseinmoradi79** [comment]
> اضافه شد

سلام لینکی که میدم برای دانلود دانلود نمیشه چرا

**Comment by hosseinmoradi79** [comment]
> > اضافه شد
> 
> سلام لینکی که میدم برای دانلود دانلود نمیشه چرا

شما لینک دانشگاه رو srm.Semnan گذاشتید 
ولی لینک کلاس ما http://vc4.semnan.ac.ir/pd88zna0xig7 هستش
مشکل از این نیست؟
