### ISSUE TITLE
[bug] 0 course(s) download and extracting finished | دانشگاه صنعتی شیراز

### ISSUE THREAD

**Issue by noOneCares123123** [soroushamdg/acd#93]
سلام خسته نباشین
فرمت لینک رو برنامه میشناسه و بعد از استارت اون پایین مینویسه دانلودینگ ولی بعد از یه چند ثانیه این پیام رو میده :
yohoo !
0 course(s) download and extracting finished
و پوشه اکسپرت هم خالیه ، چند بار با لینک های مختلف امتحان کردم بازم فرقی نکرد

----------------
لینک کلاس:

http://el.sutech.ac.ir/pfslq06ga9he/

-----------

فقط اینکه دانشگاه گفته برای استفاده از لینک کلاس هاس ضبط شده ، اول لینک کلاس آنلاین رو یه بار باز کنیم تا آدوب، آتنتیکیشن رو انجام بده بعد میتونیم لینک های ظبط شده رو باز کنیم .

------
کلاس آنلاین:
el.sutech.ac.ir/r1ii30n0rdz2/?session=breezi55utzicy8qx9scx&proto=true

**Comment by soroushamdg** [comment]
سلام، جفت لینک ها 404 میدن و خالی هستن

**Comment by noOneCares123123** [comment]
lms هر 2 لینک برای من کار میکنن حتی بدون لاگین در

![image](https://user-images.githubusercontent.com/54657144/86288732-9fc89a00-bbff-11ea-93f6-a73d1b0b86fb.png)
