### ISSUE TITLE
اضافه کردن دانشگاه صنعتی بیرجند

### ISSUE THREAD

**Issue by sarvar2715** [soroushamdg/acd#95]
سلام اضافه کردن دانشگاه صنعتی بیرجند 
http://lms.birjandut.ac.ir

**Comment by soroushamdg** [comment]
سلام، لطفا نمونه لینک کلاس ضبط شده بفرستید

**Comment by sarvar2715** [comment]
http://vc.birjandut.ac.ir/pcz8uw4vse99/?session=breeziuk96et36htbwqz6&proto=true
