### ISSUE TITLE
new school request (Lorestan University)

### ISSUE THREAD

**Issue by punisher98** [soroushamdg/acd#96]
hi...
please add lorestan university to database...
adobe connect link: https://vc.lu.ac.ir/

**Comment by soroushamdg** [comment]
سلام
لینک کار نمیکنه

**Comment by punisher98** [comment]
[image: 1.JPG]ll

‫‪Soroush M Pour‬‏ <‪notifications@github.com‬‏> در تاریخ چهارشنبه ۱ ژوئیهٔ
۲۰۲۰ ساعت ۱۹:۳۴ نوشت:‬

> سلام، ممنون  از پیگیریت
>
vc.lu.ac.ir
اینم عکسش
